# Generated by Django 3.2.6 on 2021-10-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cured', models.IntegerField(default=1)),
                ('death', models.IntegerField(default=1)),
                ('admitted', models.IntegerField(default=1)),
                ('hospital_name', models.CharField(max_length=100)),
            ],
        ),
    ]
