# Generated by Django 3.2.6 on 2021-10-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_patient_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_status',
            old_name='hospital_name',
            new_name='state',
        ),
    ]
